// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from './routes/_404.tsx';
import * as $_500 from './routes/_500.tsx';
import * as $_app from './routes/_app.tsx';
import * as $_middleware from './routes/_middleware.ts';
import * as $api_rooms from './routes/api/rooms.ts';
import * as $index from './routes/index.tsx';
import * as $rooms_id_ from './routes/rooms/[id].tsx';
import * as $filters from './islands/filters.tsx';
import * as $hooks from './islands/hooks.ts';
import * as $rooms from './islands/rooms.tsx';
import { type Manifest } from '$fresh/server.ts';

const manifest = {
  routes: {
    './routes/_404.tsx': $_404,
    './routes/_500.tsx': $_500,
    './routes/_app.tsx': $_app,
    './routes/_middleware.ts': $_middleware,
    './routes/api/rooms.ts': $api_rooms,
    './routes/index.tsx': $index,
    './routes/rooms/[id].tsx': $rooms_id_,
  },
  islands: {
    './islands/filters.tsx': $filters,
    './islands/hooks.ts': $hooks,
    './islands/rooms.tsx': $rooms,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
